name: ios
on:
  push:
    branches:
     - master
     - 'feature/**'
    paths:
      - 'src/**'
      - 'ios/**'
      - '.github/workflows/ios.yml'
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - 'ios/**'
      - '.github/workflows/ios.yml'

jobs:
  build:
    name: ios-build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: download_mode
        run: |
            wget -c -nv https://github.com/wangzhaode/mnn-llm/releases/download/qwen1.5-0.5b-chat-mnn/Qwen1.5-0.5B-Chat-MNN.zip
            unzip Qwen1.5-0.5B-Chat-MNN.zip
            mv Qwen1.5-0.5B-Chat-MNN/* ios/mnn-llm/model/qwen1.5-0.5b-chat/

      - name: build
        run: |
          ./script/ios_build.sh