name: windows
on:
  push:
    branches:
     - master
     - 'feature/**'
    paths:
      - 'src/**'
      - '.github/workflows/windows.yml'
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - '.github/workflows/windows.yml'

jobs:
  build:
    name: windows-build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: build
        run: .\script\build.ps1

      - name: download_mode
        run: |
            Invoke-WebRequest -Uri https://github.com/wangzhaode/mnn-llm/releases/download/qwen1.5-0.5b-chat-mnn/Qwen1.5-0.5B-Chat-MNN.zip -OutFile Qwen1.5-0.5B-Chat-MNN.zip
            unzip Qwen1.5-0.5B-Chat-MNN.zip

      - name: test_model
        run: |
            cd build
            .\Release\cli_demo ..\Qwen1.5-0.5B-Chat-MNN\config.json ..\resource\prompt.txt
            Exit 0